name: 'dbtformula1'
version: '1.8.3'
require-dbt-version: '>=1.3.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbtformula1'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  mph_to_kph_factor: 1.60934  
  snapshot_view_schema: PUBLIC

models:
  #+transient: false
  dbtformula1:
    staging:
      snowflake_warehouse: compute_wh
      +schema: staging
      +materialized: view
      +docs:
        node_color: "CadetBlue"
    intermediate:
      snowflake_warehouse: compute_wh
      +schema: internal
      +materialized: view
      +docs:
        node_color: "CadetBlue"
    marts:
      +materialized: table
      +schema: analytics
      aggregates:
        +docs:
          node_color: "Maroon"
        +tags: "bi"

    core:
      +materialized: table
      +schema: public
      +docs:
        node_color: "#800080"

#    ml:
#      +materialized: table
#      +schema: ml
#      prep_encoding_splitting:
#        +docs:
#          node_color: "Indigo"
#      training_and_prediction:
#        +docs:
#          node_color: "Black"

snapshots:
  dbtformula1:
    +materialized: snapshot
    +target_schema: snapshots
    +docs:
      node_colour: "Purple"
    transient: false

seeds:
  #+transient: false
  dbtformula1:
    +schema: raw